version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql84
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: dba
      MYSQL_PASSWORD: Password25$
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16
    container_name: pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: Password25$
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  pg_data:
